version: '3.4'

services:
  blazorui:
    image: blazorui
    build:
      context: .
      dockerfile: apps/BlazorUI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5010:5010"
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: gateways/PublicGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
  accounting:
    image: accountingservice
    build:
      context: .
      dockerfile: microservices/accounting/Accounting.Service/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
  transactions:
    image: transactionservice
    build:
      context: .
      dockerfile: microservices/transactions/Transaction.Service/Dockerfile     
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"      
