version: '3.4'

services:
  blazorui:
    image: ${DOCKER_REGISTRY-}blazorui
    build:
      context: .
      dockerfile: apps/BlazorUI/Dockerfile
    depends_on:    
    - rabbitmq     
    - publicgateway
    - accounting.service
    - transaction.service

  publicgateway:
    image: ${DOCKER_REGISTRY-}publicgateway
    build:
      context: .
      dockerfile: gateways/PublicGateway/Dockerfile
    depends_on:    
    - rabbitmq     
    - accounting.service
    - transaction.service

  accounting.service:
    image: ${DOCKER_REGISTRY-}accountingservice
    build:
      context: .
      dockerfile: microservices/accounting/Accounting.Service/Dockerfile
    depends_on:    
    - rabbitmq     

  transaction.service:
    image: ${DOCKER_REGISTRY-}transactionservice
    build:
      context: .
      dockerfile: microservices/transactions/Transaction.Service/Dockerfile
    depends_on:    
    - rabbitmq     

