version: '3.4'

services:
  blazorui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  publicgateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  accounting.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  transaction.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
    - 15672:15672
    - 5672:5672      