version: '3.4'

services:
  blazorui:
    image: ${DOCKER_REGISTRY-}blazorui
    build:
      context: .
      dockerfile: apps/BlazorUI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5010:80"
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: gateways/PublicGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000"
  accounting:
    image: ${DOCKER_REGISTRY-}accountingservice
    build:
      context: .
      dockerfile: microservices/accounting/Accounting.Service/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001"
  transactions:
    image: ${DOCKER_REGISTRY-}transactionservice
    build:
      context: .
      dockerfile: microservices/transactions/Transaction.Service/Dockerfile     
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002"      
